### ISSUE TITLE
How to fix - Cannot read property '0' of undefined -

### ISSUE THREAD

**Issue by sheriff-rango** [cosmos/cosmjs#1374]
Hi
I am not sure this is the issue with this package.
I can run and build my project on my local end successfully but when I deploy my products to `IONOS`, I met this error.
![image](https://user-images.githubusercontent.com/95250818/220199077-35b538e2-015f-4531-89a8-c3c30402025c.png)

Here is my deploy script.
```
# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: Deploy Now

on:
    - push
    - workflow_dispatch

jobs:
    deploy-now:
        runs-on: ubuntu-latest
        steps:
            - name: Fetch project data
              uses: ionos-deploy-now/retrieve-project-info-action@v1
              id: project
              with:
                  api-key: ${{ secrets.IONOS_API_KEY }}
                  project: ${{ secrets.IONOS_PROJECT_ID }}
                  service-host: api-eu.ionos.space

            - name: checkout
              if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
              uses: actions/checkout@v2
              with:
                  submodules: "recursive"

            - name: Setup Node
              if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
              uses: actions/setup-node@v1
              with:
                  node-version: v14.17.5

            - name: Build Node assets
              if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
              env:
                  CI: true
                  SITE_URL: ${{ steps.project.outputs.site-url }}
              run: |
                  npm install --frozen-lockfile
                  npm audit fix
                  npm run build

            - name: Deploy to IONOS
              if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
              uses: ionos-deploy-now/deploy-to-ionos-action@v1
              with:
                  project: ${{ secrets.IONOS_PROJECT_ID }}
                  branch-id: ${{ steps.project.outputs.branch-id }}
                  service-host: api-eu.ionos.space
                  api-key: ${{ secrets.IONOS_API_KEY }}
                  dist-folder: build
```

But I can build on my local end without any issues.
Please anyone help me with solving this issue.
