### ISSUE TITLE
proposal title cannot be blank: invalid proposal content at SigningStargateClient.broadcastTx

### ISSUE THREAD

**Issue by abhitidarbar** [cosmos/cosmjs#930]
We are trying to do a Submit Proposal tx using js client and getting this error.
```
Error: Broadcasting transaction failed with code 5 (codespace: gov). Log: proposal title cannot be blank: invalid proposal content at SigningStargateClient.broadcastTx
```
Msg passed from frontend.
```const msg = {
    content: {
        typeUrl: "/cosmos.gov.v1beta1.TextProposal",
        value: {
            title: "title",
            description: "description",
        },
    },
    initial_deposit: [
        {
            denom: "coin",
            amount: "1",
        },
    ],
    proposer: "address",
};
```
Msg received by chain.
```
content:
  typeurl: /cosmos.gov.v1beta1.TextProposal
  value: []
  xxx_nounkeyedliteral: {}
  xxx_unrecognized: []
  xxx_sizecache: 0
initial_deposit:
- denom: coin
  amount: "1"
proposer: address
```
cosmos-sdk version - 0.44.0
